[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Uncomment untuk set resource limits (opsional)
# [[deploy.resourceLimits]]
# memory = 1024
# cpu = 1
